password-authenticator.name=ldap
# ldap.url=ldap://host.docker.internal:389
# ldap.allow-insecure=true
ldap.url=ldaps://host.docker.internal:636
ldap.ssl.truststore.path=/home/docker-certificates/truststore.jks
ldap.ssl.truststore.password=UnIx529p
ldap.ssl.keystore.path=/home/docker-certificates/keystore.jks
ldap.ssl.keystore.password=UnIx529p

# Authorization using Trino LDAP service user
ldap.bind-dn=cn=admin,dc=openldap
ldap.bind-password=rangerR0cks!

# Exemplo com LDAP tradicional
ldap.user-bind-pattern=uid=${USER},dc=openldap

# Group-Based Authorization Restrict access by LDAP group membership:
ldap.user-base-dn=dc=openldap

## Group authorization patterns
ldap.group-auth-pattern=(&(objectClass=posixGroup)(memberUid=${USER})(cn=trino))
